spring:
  cloud:
    vault:
      token: root-token
      scheme: http
      host: localhost
      port: 8200
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
  config:
    import:
      - "vault:/secret/${spring.project.name}/${spring.application.name}/${spring.profiles.active}"